version: '3.9'

services:
  php-apache:
    image: php:8.3-apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql

  frontend:
    build: ./frontend
    ports:
      - "8000:80"  # Change the port if needed

  admin_panel:
    build: ./admin-panel
    ports:
      - "8001:80"  # Change the port if needed

  api:
    build: ./api
    ports:
      - "8002:80"  # Change the port if needed
