version: '3.9'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"          # Frontend
      - "8001:8001"      # Admin Panel
      - "8002:8002"      # API
    volumes:
      - ./frontend:/usr/share/nginx/html/frontend
      - ./admin-panel:/usr/share/nginx/html/admin-panel
      - ./api:/usr/share/nginx/html/api
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./frontend:/var/www/html/frontend
      - ./admin-panel:/var/www/html/admin-panel
      - ./api:/var/www/html/api
      - ./src:/var/www/html/src
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    expose:
      - "9000"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
